### ISSUE TITLE
Event space statement

### ISSUE THREAD

**Issue by witchlane** [learn-co-curriculum/dsc-1-08-08-introduction-to-probability#2]
I would think the following statement would mean that the "Event Space" should actually be equal to {1,3,5) and not {2,4,6} as stated.  Screen shot below:  
![image](https://user-images.githubusercontent.com/44211854/51766499-bc76af00-20a8-11e9-89f1-07f9fdbc294c.png)

Thanks.

**Comment by mathymitchell** [comment]
Thanks for the feedback! You are indeed correct and we've fixed the lesson to match your suggestion.
